name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Printing Greetings text
        run: echo "welcoming..."
      - name: Print goodbye
        run: echo "your first jobe done - bye bye!!!"
    
